apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: 3.17.1
    helm:
      releaseName: gatekeeper

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system

  #to stop ArgoCD from constantly marking CRDs OutOfSync
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: "*.gatekeeper.sh"
      jsonPointers:
        - /spec

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

