apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.4
    helm:
      releaseName: loki-stack
      values: |
        # Run a simple, single-binary Loki for local dev
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          # Minimal storage config to satisfy the chart & use local filesystem
          storage:
            type: filesystem
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
