apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.4
    helm:
      releaseName: loki-stack
      values: |
        # Run Loki in simple monolithic (SingleBinary) mode for local dev
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false

          # Local filesystem storage inside the cluster (k3d/docker),
          storage:
            type: filesystem
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin

          # Use built-in test schema (no real persistence guarantees, fine for dev)
          useTestSchema: true

        # One single-binary replica
        singleBinary:
          replicas: 1

        # Disable scalable modes so validation stops complaining
        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

