apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    helm:
      releaseName: otel-collector
      values: |
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
        config:
          receivers:
            otlp:
              protocols:
                http:
                grpc:
          processors:
            batch: {}
          exporters:
            otlp/tempo:
              endpoint: tempo.observability.svc.cluster.local:4317
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/tempo]
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]